# get mutation distribution values
# check the difference between intronic and exonic regions:

#' Plot the difference between dnds
#'
#' @param mm mutation matrix generated by the function \code{\link{muts_to_mat}}. Rownames are 96-trinucleotides, and colnames are sampleIDs
#' @param dnds_intron Output of \link[wintr::dndscv_intron]{dndscv_intron} function containing mutation rates

#'
#' @returns list with: 1) Overview plot of the mutation rates, 2) overall mutation rate and 3) mutation type specific mutation rates
#' @importFrom patchwork wrap_plots
#' @export
#'
#' @examples
check_mutation_distribution = function(mm, dnds_intron) {

  # whole-genome rates
  trinuc_counts_wg = hg19_trinuc_counts |>
    dplyr::rename(trinuc = trinucleotide) |>
    left_join(triplet_match_substmodel |> select(trinuc, triplet) |> distinct(), by = "trinuc")
  trinuc_muts_wg = data.frame(mutations = rowSums(mm)) |>
    rownames_to_column("triplet") # total trinucleotide mutations
  wg_mutrate = left_join(trinuc_counts_wg, trinuc_muts_wg, by = "triplet") |>
    mutate(mutrate = mutations / trinuc_counts) |>
    arrange(match(triplet, TRIPLETS_96))

  # total exonic + genic mutation rates
  transcribed_muts = triplet_match_substmodel |>
    mutate(transcribed_counts = rowSums(dnds_intron$L),
           transcribed_muts = rowSums(dnds_intron$N)) |>
    group_by(triplet) |>
    summarize(transcribed_counts = sum(transcribed_counts),
              transcribed_muts = sum(transcribed_muts)) |>
    mutate(mutrate = transcribed_muts / transcribed_counts)

  # mutrate in the intergenic regions
  intergenic_rate = data.frame(triplet = TRIPLETS_96,
                               intergenic_counts = wg_mutrate$trinuc_counts - transcribed_muts$transcribed_counts,
                               intergenic_muts = wg_mutrate$mutations - transcribed_muts$transcribed_muts) |>
    mutate(mutrate = intergenic_muts / intergenic_counts)

  list_mutrates = list(whole_genome = wg_mutrate, transcribed = transcribed_muts, intergenic = intergenic_rate)
  mutrates_regions = lapply(list_mutrates, dplyr::select, triplet, mutrate) |>
    rbindlist(idcol = "region") |>
    left_join(triplet_match_substmodel |> select(triplet, type) |> distinct(), by = "triplet")

  mutrates_type = mutrates_regions |>
    group_by(region, type) |>
    summarize(mutrate = mean(mutrate), .groups = "drop")
  mutrates_type_plot =
    ggplot(mutrates_type, aes(x = type, fill = region, y = mutrate)) +
    geom_col(position = "dodge") +
    cowplot::theme_cowplot() +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    labs(x = NULL)

  mutrates_overall = mutrates_regions |>
    group_by(region) |>
    summarize(mutrate = mean(mutrate))
  mutrates_overall_plot = ggplot(mutrates_overall, aes(x = region, y = mutrate)) +
    geom_col(position = "dodge") +
    cowplot::theme_cowplot() +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    labs(x = NULL)

  mutrates_trinuc = mutrates_regions |>
    filter(region != "whole_genome") |>
    ggplot(aes(x = triplet, y = mutrate, alpha = region, fill = type)) +
    geom_col(position = 'dodge') +
    cowplot::theme_cowplot() +
    scale_alpha_manual(values = c(0.25, 1)) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    scale_fill_manual(values = COLORS6) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    labs(x = NULL)

  ratio_plot = mutrates_regions |>
    pivot_wider(names_from = region, values_from = mutrate) |>
    mutate(across(c(transcribed, intergenic), ~ . / whole_genome)) |>
    pivot_longer(c(transcribed, intergenic), names_to = "region", values_to = "mutrate") |>
    left_join(triplet_match_substmodel |> select(triplet, type) |> distinct(), by = c("triplet", "type")) |>
    ggplot(aes(x = triplet, y = mutrate, fill = type, alpha = region)) +
    geom_col(position = 'dodge') +
    geom_hline(yintercept = 1, linetype = "dashed") +
    cowplot::theme_cowplot() +
    scale_alpha_manual(values = c(0.25, 1)) +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    scale_fill_manual(values = COLORS6) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    labs(x = NULL, y = "ratio mutrate inter")

  # combine plots to make an overview plot
  design = "
    12
    33
    44"

  overview_plot = wrap_plots(mutrates_overall_plot, mutrates_type_plot, mutrates_trinuc, ratio_plot ) + plot_layout(design = design, widths = c(1,2), guides = 'collect') +
    plot_annotation(tag_levels = "A")

 # return list with outputs
  list(plot = overview_plot,
       mutrates_overall = mutrates_overall,
       mutrates_type = mutrates_type)
}
